# reference for schema.yml:
# https://docs.oracle.com/en-us/iaas/Content/ResourceManager/Concepts/terraformconfigresourcemanager.htm#exampleschema

title: Hub-Spoke Stack
description: "Deployment of network and compute layers of a hub-spoke architecture."
schemaVersion: 1.1.0

variableGroups:
- title: "Invisible Variables"
  variables:
  - ${tenancy_ocid}
  - ${region}
- title: "Network Layer"
  variables:
  - ${deploy_network}
  # depend on deploy network
  # hub
  - ${network_hub_compartment_ocid}
  - ${network_hub_name}
  - ${network_hub_cidr}
  - ${network_hub_num_network_partitions}
  - ${network_hub_use_ngw}
  - ${network_hub_use_drg}
  - ${network_client_premises_cidr} # depends on use drg
  - ${hub_add_subnet}
  - ${hub_subnet_b_is_public} # depends on add subnet
  # spoke
  - ${num_spoke_networks}
  - ${network_spoke_compartment_ocid}
  - ${network_spoke_name}
  - ${network_spoke_cidr_supernet}
  - ${network_spoke_cidr_supernet_newbits}
  - ${network_spoke_num_network_partitions}
  - ${network_spoke_use_ngw}
  - ${network_spoke_use_sgw}
  - ${spoke_subnet_a_is_public}
  - ${spoke_add_subnet}
  - ${spoke_subnet_b_is_public} # depends on add subnet
- title: "Compute Layer"
  variables:
  - ${deploy_compute}
    # depend on deploy compute
    # hub
  - ${compute_hub_name}
  - ${compute_hub_availability_domain}
  - ${compute_hub_compartment_ocid}
  - ${compute_hub_shape}
  - ${compute_hub_shape_config_memory_in_gbs} # depends on shape
  - ${compute_hub_shape_config_ocpus} # depends on shape
  - ${compute_hub_image_ocid}
  - ${compute_hub_boot_volume_size_in_gbs}
  - ${compute_hub_existing_subnet_ocid} # depends on (not) deploy network
  - ${compute_hub_num_nodes}
  # spoke
  - ${compute_spoke_name}
  - ${compute_spoke_availability_domain}
  - ${compute_spoke_compartment_ocid}
  - ${compute_spoke_shape}
  - ${compute_spoke_shape_config_memory_in_gbs} # depends on shape
  - ${compute_spoke_shape_config_ocpus} # depends on shape
  - ${compute_spoke_image_ocid}
  - ${compute_spoke_boot_volume_size_in_gbs}
  - ${compute_spoke_existing_subnet_ocid}
  - ${compute_spoke_num_nodes}

# invisible variables
variables:
  tenancy_ocid:
    type: string
    required: true
    description: "Tenancy OCID is an authorization variable."
    title: "Tenancy OCID"
    visible: false
  region:
    type: string
    required: true
    description: "Region Identifier to specify the region in which the deployment will take place (e.g. us-phoenix-1)."
    title: "Region"
    visible: false

# network layer
  deploy_network:
    type: boolean
    required: true
    description: "Deploy the network layer of the hub-and-spoke topology?"
    title: "Deploy Network Layer"
    default: true
# hub
  network_hub_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    description: "Deploy hub network in which compartment?"
    title: "Hub Compartment"
    visible: ${deploy_network}
    default: samuel
  network_hub_name:
    type: string
    required: true
    description: "Friendly string to include in hub network-layer resources' names."
    title: "Hub Name"
    default: hub
    visible: ${deploy_network}
  network_hub_cidr:
    type: string
    required: true
    description: "Range of IP addresses to use for the hub Virtual Cloud Network (VCN). This value should not overlap with the value for \"Network Prefix to Supernet All Spoke VCN CIDRs\"."
    title: "Hub CIDR"
    default: 10.0.0.0/24
    visible: ${deploy_network}
  network_hub_num_network_partitions:
    type: integer
    required: true
    description: "Number of partitions to divide the hub VCN CIDR into. This will influence the size of any subnets deployed in the hub VCN."
    title: "Number of Network Partitions for Hub VCN"
    default: 2
    minimum: 2
    visible: ${deploy_network}
  network_hub_use_ngw:
    type: boolean
    required: true
    description: "Provision a Network Address Translation Gateway (NAT GW or NGW) as part of each hub network. Provides outbound-only access from a network in OCI to the internet."
    title: "Hub Use NGW"
    default: true
    visible: ${deploy_network}
  network_hub_use_drg:
    type: boolean
    required: true
    description: "Provision a Dynamic Routing Gateway (DRG) as part of the Hub network."
    title: "Hub Use DRG"
    default: true
    visible: ${deploy_network}
  network_client_premises_cidr:
    type: string
    required: true
    description: "The CIDR of customer premises. With configuration of IPSec VPN or FastConnect to the DRG (not included in this stack), private connectivity between client premises and OCI can be established."
    title: "Client Premises CIDR"
    default: 172.1.0.0/16
    visible:
      and:
        - ${network_hub_use_drg}
        - ${deploy_network}
  hub_add_subnet:
    type: boolean
    required: true
    description: "Deploy an additional subnet within the hub VCN?"
    title: "Hub Add Subnet"
    default: true
    visible: ${deploy_network}
  hub_subnet_b_is_public:
    type: boolean
    required: true
    description: "Will the additional subnet in the hub VCN allow public IPs?"
    title: "Allow Public IPs in Additional Hub Subnet"
    visible:
      and:
        - ${deploy_network}
        - ${hub_add_subnet}
# spoke network
  num_spoke_networks:
    type: integer
    required: true
    description: "How many spoke VCNs will be deployed in this hub-and-spoke stack?"
    title: "Number of Spokes"
    default: 2
    minimum: 0
    visible: ${deploy_network}
  network_spoke_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    description: "Deploy spoke network in which compartment?"
    title: "Spoke Compartment"
    visible: ${deploy_network}
    default: samuel
  network_spoke_name:
    type: string
    required: true
    description: "Friendly string to include in hub network-layer resources' names."
    title: "Spoke Name"
    default: student
    visible: ${deploy_network}
  network_spoke_cidr_supernet:
    type: string
    required: true
    description: "Range of IP Addresses that serves as a network prefix for all spoke Virtual Cloud Networks (VCNs). This value should not overlap with the value for \"Hub CIDR\"."
    title: "Network Prefix to Supernet All Spoke VCN CIDRs" # when you change this string, change all occurrences in this file.
    default: 10.1.0.0/16
    visible: ${deploy_network}
  network_spoke_cidr_supernet_newbits:
    type: integer
    required: true
    description: "Number of new bits to add to the network prefix, \"Network Prefix to Supernet All Spoke VCN CIDRs\", to result in spoke VCNs whose ranges are contained within this extension of the network prefix. E.g. extending a network prefix of 10.1.0.0/16 by 8 bits will result in spoke VCNs of range 10.1.X.0/24, such that: spoke 1: 10.1.0.0/24, spoke 2: 10.1.1.0/24, etc."
    title: "New Bits"
    default: 8
    visible: ${deploy_network}
  network_spoke_num_network_partitions:
    type: enum
    enum:
    - 2 # this is the min number of partitions we can make in a VCN so that CIDR ranges can be defined for our minimum number of 2 subnets (1 X public + 1 X private) per VCN in this project.
    - 4
    - 8
    - 16
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
    - 2048
    - 4096
    - 8192
    - 16384
    - 32768 # this is the max number of partitions we can make in a /16 VCN (largest VCN you can make in OCI) so that CIDR ranges can be defined for our minimum number of 2 subnets (1 X public + 1 X private) per VCN in this project.
    required: true
    description: "Number of partitions to divide each spoke VCN CIDR into. This will influence the size of any subnets deployed in each spoke VCN."
    title: "Number of Network Partitions for each Spoke VCN"
    default: 2
    minimum: 2
    visible: ${deploy_network}
  network_spoke_use_ngw:
    type: boolean
    required: true
    description: "Provision a Network Address Translation Gateway (NAT GW or NGW) as part of each spoke network. Provides outbound-only access from a network in OCI to the internet."
    title: "Spoke Use NGW"
    default: true
    visible: ${deploy_network}
  network_spoke_use_sgw:
    type: boolean
    required: true
    description: "Provision a Service Gateway (SGW) as part of each Spoke network. Provides access to Oracle Services Network, which includes such services as Object Storage, Monitoring, Autonomous Database, etc."
    title: "Spoke Use SGW"
    default: true
    visible: ${deploy_network}
  spoke_subnet_a_is_public:
    type: boolean
    required: true
    description: "Will the subnet in the spoke VCN allow public IPs?"
    title: "Allow Public IPs in Spoke Subnet"
    visible:
      and:
        - ${deploy_network}
  spoke_add_subnet:
    type: boolean
    required: true
    description: "Deploy an additional subnet within the hub VCN?"
    title: "Spoke Add Subnet"
    default: true
    visible: ${deploy_network}
  spoke_subnet_b_is_public:
    type: boolean
    required: true
    description: "Will the additional subnet in the spoke VCN allow public IPs?"
    title: "Allow Public IPs in Additional Spoke Subnet"
    visible:
      and:
        - ${deploy_network}
        - ${spoke_add_subnet}

# deploy compute
  deploy_compute:
    type: boolean
    required: true
    description: "Deploy the compute layer of the hub-and-spoke topology?"
    title: "Deploy Compute Layer"
    default: true
# hub
  compute_hub_name:
    type: string
    required: true
    description: "Friendly string to include in hub compute-layer resources' names."
    title: "Hub Name"
    default: jumpserver
    visible: ${deploy_compute}
  compute_hub_availability_domain:
    type: enum
    enum:
      - 1
      - 2
      - 3
    required: true
    description: "Availability Domain (AD) for each hub compute instance."
    title: "Hub AD"
    visible: ${deploy_compute}
  compute_hub_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    description: "Compartment OCID for each hub compute instance."
    title: "Hub Compartment"
    visible: ${deploy_compute}
    default: samuel
  compute_hub_shape:
    type: enum
    enum:
      - "VM.Standard2.1"
      - "VM.Standard2.2"
      - "VM.Standard2.4"
      - "VM.Standard2.8"
      - "VM.Standard2.16"
      - "VM.Standard2.24"
      - "VM.Standard.E3.Flex"
      - "VM.Standard.E4.Flex"
      - "BM.Standard2.52"
      - "BM.HPC2.36"
    required: true
    description: "Template that specifies the amount of resources (e.g. CPUs, amount of memory, etc.) that are assigned to each hub compute instance."
    title: "Hub Shape"
    default: "VM.Standard2.1"
    visible: ${deploy_compute}
  compute_hub_shape_config_memory_in_gbs:
    type: integer
    required: true
    description: "Amount of memory in GiB for each Hub compute instance."
    title: "Hub Memory"
    default: 16
    maximum: 1024
    minimum: 1
    visible:
      and:
        - eq:
          - ${compute_hub_shape}
          or:
            - "VM.Standard.E3.Flex"
            - "VM.Standard.E4.Flex"
        - ${deploy_compute}
  compute_hub_shape_config_ocpus:
    type: integer
    required: true
    description: "Number of OCPUs for hub compute instances."
    title: "Hub Number of OCPUs"
    default: 1
    maximum: 64
    minimum: 1
    visible:
      and:
          - eq:
            - ${compute_hub_shape}
            or:
            - "VM.Standard.E3.Flex"
            - "VM.Standard.E4.Flex"
          - and:
            - ${deploy_compute}
  compute_hub_image_ocid:
    type: string
    required: true
    description: "Oracle Cloud Identifier (OCID) that corresponds to a virtual hard drive template for hub compute instances. Determines the operating system and other software for the machine. These OCIDs are typically region-specific."
    visible: ${deploy_compute}
    default: ocid1.image.oc1..aaaaaaaatmfegrt4uzjgmcemh3vrk46f7ileqcfohhas56hi3pnjhp4nfhoq
  compute_hub_boot_volume_size_in_gbs:
    type: integer
    required: true
    description: "Boot Volume size in GiB for hub compute instances."
    title: "Hub Boot Volume Size"
    default: 64
    maximum: 16384
    minimum: 50
    visible: ${deploy_compute}
  compute_hub_existing_subnet_ocid:
    type: string
    required: true
    description: "OCID that corresponds to an existing subnet in which hub compute instances will be deployed."
    title: "Hub Existing Subnet"
    visible:
      and:
        - not: 
          - ${deploy_network}
        - and:
          - ${deploy_compute}
    dependsOn:
      compartmentID: ${compute_hub_compartment_ocid}
  compute_hub_num_nodes:
    type: integer
    required: true
    description: "How many compute instances will be deployed in each subnet of the hub VCN?."
    title: "Hub Number of Nodes per Subnet"
    default: 1
    minimum: 0
    visible: ${deploy_compute}
# spoke
  compute_spoke_name:
    type: string
    required: true
    description: "Friendly string to include in spoke compute-layer resources' names."
    title: "Spoke Name"
    default: student
    visible: ${deploy_compute}
  compute_spoke_availability_domain:
    type: enum
    enum:
      - 1
      - 2
      - 3
    required: true
    description: "Availability Domain (AD) for each spoke compute instance."
    title: "Spoke AD"
    visible: ${deploy_compute}
  compute_spoke_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    description: "Compartment OCID for each spoke compute instance."
    title: "Spoke Compartment"
    visible: ${deploy_compute}
    default: samuel
  compute_spoke_shape:
    type: enum
    enum:
      - "VM.Standard2.1"
      - "VM.Standard2.2"
      - "VM.Standard2.4"
      - "VM.Standard2.8"
      - "VM.Standard2.16"
      - "VM.Standard2.24"
      - "VM.Standard.E3.Flex"
      - "VM.Standard.E4.Flex"
      - "BM.Standard2.52"
      - "BM.HPC2.36"
    required: true
    description: "Template that specifies the amount of resources (e.g. CPUs, amount of memory, etc.) that are assigned to each spoke compute instance."
    title: "Spoke Shape"
    default: "VM.Standard2.1"
    visible: ${deploy_compute}
  compute_spoke_shape_config_memory_in_gbs:
    type: integer
    required: true
    description: "Amount of memory in GiB for each Spoke compute instance."
    title: "Spoke Memory"
    default: 16
    maximum: 1024
    minimum: 1
    visible:
      and:
        - eq:
          - ${compute_spoke_shape}
          or:
            - "VM.Standard.E3.Flex"
            - "VM.Standard.E4.Flex"
        - ${deploy_compute}
  compute_spoke_shape_config_ocpus:
    type: integer
    required: true
    description: "Number of OCPUs for spoke compute instances."
    title: "Spoke Number of OCPUs"
    default: 1
    maximum: 64
    minimum: 1
    visible:
      and:
          - eq:
            - ${compute_spoke_shape}
            or:
            - "VM.Standard.E3.Flex"
            - "VM.Standard.E4.Flex"
          - and:
            - ${deploy_compute}
  compute_spoke_image_ocid:
    type: string
    required: true
    description: "Oracle Cloud Identifier (OCID) that corresponds to a virtual hard drive template for spoke compute instances. Determines the operating system and other software for the machine. These OCIDs are typically region-specific."
    visible: ${deploy_compute}
    default: ocid1.image.oc1..aaaaaaaatmfegrt4uzjgmcemh3vrk46f7ileqcfohhas56hi3pnjhp4nfhoq
  compute_spoke_boot_volume_size_in_gbs:
    type: integer
    required: true
    description: "Boot Volume size in GiB for spoke compute instances."
    title: "Spoke Boot Volume Size"
    default: 64
    maximum: 16384
    minimum: 50
    visible: ${deploy_compute}
  compute_spoke_existing_subnet_ocid:
    type: string
    required: true
    description: "OCID that corresponds to an existing subnet in which spoke compute instances will be deployed."
    title: "Spoke Existing Subnet"
    visible:
      and:
        - not: 
          - ${deploy_network}
        - and:
          - ${deploy_compute}
    dependsOn:
      compartmentID: ${compute_spoke_compartment_ocid}
  compute_spoke_num_nodes:
    type: integer
    required: true
    description: "How many compute instances will be deployed in each subnet of the spoke VCN?."
    title: "Spoke Number of Nodes per Subnet"
    default: 2
    minimum: 0
    visible: ${deploy_compute}